export enum ENVEnum {
  NODE_ENV = 'NODE_ENV',
  MONGODB_URI = 'MONGODB_URI',

  PORT = 'PORT',
  BASE_URL = 'BASE_URL',

  JWT_SECRET = 'JWT_SECRET',
  JWT_EXPIRES_IN = 'JWT_EXPIRES_IN',

  OLLAMA_BASE_URL = 'OLLAMA_BASE_URL',
  OLLAMA_MODEL = 'OLLAMA_MODEL',

  REDIS_HOST = 'REDIS_HOST',
  REDIS_PORT = 'REDIS_PORT',

  SUPER_ADMIN_EMAIL = 'SUPER_ADMIN_EMAIL',
  SUPER_ADMIN_PASS = 'SUPER_ADMIN_PASS',
}
