services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PACKAGE_NAME=${PACKAGE_NAME}
        - PACKAGE_VERSION=${PACKAGE_VERSION}
    container_name: ${PACKAGE_NAME}_api
    restart: always
    env_file:
      - .env
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://root:root@mongodb:27017/${PACKAGE_NAME}_db?authSource=admin

      REDIS_HOST: redis
      REDIS_PORT: 6379

      BASE_URL: http://0.0.0.0:3000
      PORT: 3000

      OLLAMA_BASE_URL: http://ollama:11434
      OLLAMA_MODEL: llama3.2
    ports:
      - '3000:3000'
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: >
      sh -c "
        echo '🏁 Waiting for MongoDB...';
        sleep 5;
        echo '🚀 Starting app...';
        pnpm start
      "
    volumes:
      - files-data:/app/uploads
      - temp-data:/app/tmp
      - ./uploads:/app/uploads
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://0.0.0.0:3000/health']
      interval: 30s
      timeout: 10s
      retries: 5

  mongodb:
    image: mongo:8
    container_name: ${PACKAGE_NAME}_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: ${PACKAGE_NAME}_db
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    ports:
      - '127.0.0.1:27017:27017'
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', 'db.adminCommand("ping")']
      interval: 10s
      timeout: 5s
      retries: 5

  mongo-express:
    image: mongo-express
    container_name: ${PACKAGE_NAME}_mongo_express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASS}
    ports:
      - '8081:8081'
    depends_on:
      mongodb:
        condition: service_healthy

  redis:
    image: redis:8
    container_name: ${PACKAGE_NAME}_redis
    command:
      [
        'redis-server',
        '--appendonly',
        'yes',
        '--bind',
        '0.0.0.0',
        '--protected-mode',
        'no',
      ]
    ports:
      - '127.0.0.1:6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 5
    restart: always

  ollama:
    image: ollama/ollama:latest
    container_name: ${PACKAGE_NAME}_ollama
    ports:
      - '127.0.0.1:11434:11434'
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

volumes:
  mongodb_data:
  files-data:
  temp-data:
  ollama_data:

networks:
  default:
    name: ${PACKAGE_NAME}_network
    labels:
      - 'project=${PACKAGE_NAME}'
